#! /bin/bash

TCOL="#eee8d5"   
ACOL="#b58900"   
PCOL="#859900"

MPDSTATE=$(mpc | sed -e '2 !d' -e 's/^.*\[//' -e 's/\].*$//')

if [ $MPDSTATE == "playing" ]; then
    echo "<fc=$ACOL>$(mpc current | sed "s/ - /\<\/fc\> - \<fc=$TCOL>/")</fc>"
elif [ $MPDSTATE == "paused" ]; then
    echo "<fc=$PCOL>$(mpc current)</fc>"
fi
